### ISSUE TITLE
Qustion about the input dimension namescomputational sequence version

### ISSUE THREAD

**Issue by Zhong0x29a** [georgepar/mmlatch#3]
Firstly, I express my gratitude for your excellent work! I am currently trying to reproduce the results in your paper, but I encountered an issue with the code.

The program is asking for an input labeled "Please input dimensional namescomputational sequence version for <CMU_MOSEI_TimestampedWords> computational sequence". I am unsure what this means and whether I need to enter specific information or edit the source code.

![screenshot_20230226_193619](https://user-images.githubusercontent.com/30078651/221548834-d295480d-bbf0-4946-b07d-853cfcad1319.png)

Could you please clarify what "dimensional namescomputational sequence version" refers to, and provide any guidance on how to proceed?

Thank you in advance for your help, and I appreciate your time and effort in addressing this issue.

**Comment by snowbling** [comment]
Hello,I have the same problem. At first, I thought it was to enter the corresponding python version number. Later, I found that I understood it wrong. I wonder if you are still reproducing this project now.

**Comment by Zhong0x29a** [comment]
@snowbling 

Hi, I am now still reproducing this project. However, this problem still confusing me...

My temporary solution is: just press an ENTER when come across an input request, which seemed work, since the final result are close to the paper. 

I am still looking for a better solution or an interpretation (of this phenomenon)...

**Comment by georgepar** [comment]
@Zhong0x29a  @snowbling

The solution proposed by @Zhong0x29a is correct. This "version" input is related to the [CMU Multimodal SDK](https://github.com/A2Zadeh/CMU-MultimodalSDK). I don't think it's necessary to input any particular feature version, but I haven't found a way to stop it from asking.

**Comment by Zhong0x29a** [comment]
@georgepar 

This may be an solution to stop it from asking for input:

I tried modifying the source code at `cmusdk>mmsdk>mmdatasdk>computational_sequence>computational_sequence.py:142`, changing the `log.status(...)` parameter from `require_input=True` to `require_input=False`, then ran the program with nohup, which would ignore the input request. And it worked. (If directly ran the program with nohup without changing the source code, it would case some error and the program would be terminated. )
